### ISSUE TITLE
Help with journal.schema.yml and markdown template

### ISSUE THREAD

**Issue by ericthomas1** [dendronhq/schema-library#2]
Hello,

Can someone see what I'm missing? 

**Goal:** 
- Every day, open VS Code, click `CTRL+SHFT+I` to open a new Journal Entry with the Markdown template shown below populated

**Issue:**
- `CTRL+SHFT+I` results in a blank Journal Entry, no template is applied

**Setup:**

**- `journal.schema.yml` file in the `/vault` directory:**

```
version: 1
schemas:
- id: journal
  title: journal
  desc: ""
  parent: root
  children:
    - daily
    - weekly
    - yearly
- id: daily
  namespace: true
  template:
    id: journal.template.daily.md
    type: note
- id: weekly
  namespace: true
- id: yearly
  namespace: true
```

**- `journal.template.daily.md` file also in `/vault` directory:**

```
##### Login:        
##### Logout:       
##### Duration:     

##### Skills and tools used:

| Skill/Tool/Language | Notes |
| ----------------------| ------- |
|                                 |            |

##### To-do List:


##### Context:


##### TIL's:


##### Big News:
```

**- `CTRL+SHFT+I` results in:**

```
---
id: oyjMFSBPTP79Jn4D5Edp6
title: '2021-06-29'
desc: ''
updated: 1624983615078
created: 1624983615078
---
```

**- Need it to be:**

```
---
id: oyjMFSBPTP79Jn4D5Edp6
title: '2021-06-29'
desc: ''
updated: 1624983615078
created: 1624983615078
---

##### Login:        
##### Logout:       
##### Duration:     

##### Skills and tools used:

| Skill/Tool/Language | Notes |
| ----------------------| ------- |
|                                 |            |

##### To-do List:


##### Context:


##### TIL's:


##### Big News:
```
